### ISSUE TITLE
Doc Gen Improvements

### ISSUE THREAD

**Issue by ScottCarda-MS** [microsoft/qsharp#1204]
The Docs Team has suggested several improvements to the doc generator tool.

- [x] Colons in the metadata values will break the doc team's yaml interpreter. There were a handful of generated files that have "Warning:" or "Note:" in the summary section. Currently, the docs team has to manually fix this in the file before publishing. The suggestion here is to wrap the summary section of the metadata in quotations. (#1206)
- [x] There are about two dozen files that have "See Also" references to other topics. It would be nice if those could be live links. (#2041)
- [x] Files for Namespaces containing lists of the namespaces's contents (along with links), along with changing the "Namespace" section of the files into links to the namespace file. (#2012)

**Comment by Pulkit1822** [comment]
@ScottCarda-MS , I would like to work on this issue.
