### ISSUE TITLE
Adaptive Profile QIR generation

### ISSUE THREAD

**Issue by cesarzc** [microsoft/qsharp#1294]
The work to generate QIR that is compliant with the Adaptive Profile specification can be divided into a few major categories.

# Runtime Capabilities Analysis (RCA)
RCA is the process of determining the capabilities a quantum kernel needs to be able to run a particular program. RCA also identifies program elements that can be pre-computed before execution on a quantum kernel and does not consider these elements when determining the capabilities.
- [x] Detailed analysis for most of the Q# language (#1164).
- [x] Set dynamic qubits value kind as dynamic (#1304).

# Runtime Capabilities Check Pass
Once RCA has identified the capabilities needed to run a particular program, it can be used to check whether the program can run on a particular target, and if not, provide compile-time feedback to the user about why.
- [x] Implement runtime capabilities check pass (#1291).
- [x] Type of the entry expression should be part of the check (#1417).
- [x] Full support for partial eval of closures with captures (#1498)
- [x] Disallow dynamic exponential operations (if possible only when the exponential is dynamic) (#1539)

# Partial Evaluation
Partial evaluation is the process of generating a residual program by evaluating all purely classical computations. It starts with an entry expression for a program in the Flattened Intermediate Representation (FIR), uses RCA to identify purely classical computations and produces a program in the Residualized Intermediate Representation (RIR).
- [x] Design the RIR data structure (#1292).
- [x] Implement partial evaluation.
    - [x] Support custom backend to verify no quantum operations are simulated (#1332).
    - [x] Support for intrinsic unitary operations with classical arguments (#1334).
    - [x] Support for proper qubit and measurement results management, including optimal qubit allocation (#1367).
    - [x] Set qubit and result counts in output program (#1383).
    - [x] Output recording (#1387).
    - [x] Runtime failure for Result literals in output (#1409).
    - [x] Full support for non-intrinsic function/operation calls (#1386).
    - [x] Support for controlled functors (#1452).
    - [x] Support loop unrolling (#1378).
    - [x] Support basic branching based on measurement results. i.e. calls to unitary operations inside branches (#1376).
    - [x] Support for hybrid return expressions (#1421).
    - [x] Support for assignment, array repeat, array in-place concatenation, array in-place update of value at index, and array access to value at index (#1480).
    - [x] Support for dynamic binary operations and dynamic assign binary operations on Booleans and integers (except LHS dynamic Boolean and exponentiation) (#1499).
    - [x] Support LHS dynamic Booleans (#1540).
    - [x] Support exponentiation (#1541).
    - [x] Support for unary operations (#1485).
    - [x] Support array slicing via ranges in index expressions (#1546).
    - [x] Make early returns raise an `Unimplemented` error (#1544).
    - [x] Perform eval-time RCA check for previously unresolved callables (#1497)

# RIR Transformation Passes
Some patterns might require enough complexity to eliminate or transform that they are better separated into RIR -> RIR transformation passes. This allows both the Partial Evaluation that precedes this step and the QIR Generation that follows to remain focused on their specific complexities.
- [x] Disallow branching on literal by changing RIR structure (#1360)
- [x] Defer Measurements pass (#1319)
- [x] Unreachable code pass (#1319)
- [x] Qubit Reindex on Reuse pass (#1342)
- [x] SSA pass (aka mem2reg)
   - [x] Remap block identifiers to be ordered by control flow graph (#1353)
   - [x] Replace all but final Store instructions within block with SSA (#1363)
   - [x] Calculate dominator tree for blocks (#1354)
   - [x] Replace remaining Store instructions with Phi instructions in later blocks (#1363)
   - [x] Validation pass that ensures SSA values correctly dominate usage (#1358)
- [x] Move passes into RIR crate (#1341)
- [x] Type consistency pass (#1397)
- [x] Block optimization pass that eliminates trivial jumps (blocks with only one successor, where that successor has only one predecessor) (#1407)

# QIR Generation 
Once the compiler has performed partial evaluation and transformed the program into RIR, the compiler uses it as input to the code generation step, which produces specification-compliant QIR in text form.
- [x] Support "straight-line" code, effectively base profile, where only void function calls are expected. (#1305)
- [x] Support mid-circuit measurement with branching based on measurement results but not arbitrary mutable Booleans. (#1311)
- [x] Support codegen of Phi nodes. (#1337)
- [x] Support codegen of integer arithmetic operations. (#1337)
- [x] Support codegen of Boolean operations and comparisons. (#1337)
- [x] Support codegen of bitshift operations. (#1337)

# Integration
As the other four major pieces are completed, they can start being integrated into the rest of the QDK.
- [x] Create feature flag for Adaptive Profile QIR generation.  (#1347)
- [x] Extend target configuration to support more than just `Unrestricted` and `Base`. (#1347)
    - [x] Support for VSCode. (#1347)
    - [x] Support for Python.   (#1347)
- [x] Integrate the runtime capabilities check pass into the language service.
  - [x] OpenProject (#1347)
  - [x] Notebook (#1373)
- [x] Integrate Adaptive Profile QIR generation into the incremental compiler.
  - [x] Wire everything together. (#1347)
  - [x] Implement code generation
    - [x] OpenProject (#1375)
    - [x] Notebook (#1375)
    - [x] Python (#1375)
- [x] Unify QIR generation paths (#1400)
- [x] Replace base profile check pass with RCA. (#1523)

# End-to-end Testing
- [x] Test correctness of program execution on QIR targets

# Release
- [x] Remove feature toggles (#1523)
- [x] Enable Python Base profile code generation (#1523)
 
# Related Items
- #1306 
- #1414 
- #1433
- #1529
