### ISSUE TITLE
Q# Structs

### ISSUE THREAD

**Issue by ScottCarda-MS** [microsoft/qsharp#1515]
We want to add structs to the Q# language. This will allow us to alleviate some of the pain-points with existing language constructs, and give us the opportunity to refactor parts of the compiler that need improvement.

Tasks:
- [x] Add struct syntax to the parser and AST. #1573 
- [x] Additional changes will need to be made to the Path nodes to allow for field accessor syntax. #1636 
- [x] Lower struct AST nodes to HIR nodes. This will lower structs into UDTs. #1573 
- [x] Refactor UDT implementation in AST/HIR to allow fields to be referenced using the ref mechanism in the compiler. #1609 
- [x] Add lint warnings to deprecate UDT syntax. #1660 
- [x] Make necessary adjustments to language server. (hover, goto def, find refs) #1609 
- [x] Update syntax highlighting for new keywords. #1691 
- [x] Update docs.
- [x] Add code samples. #1797

**Comment by sezna** [comment]
For all intents and purposes this is done -- samples will come in right after the docs land.
