### ISSUE TITLE
User experience improvements for QIR generation

### ISSUE THREAD

**Issue by cesarzc** [microsoft/qsharp#1529]
- [x] Underline span in user code that caused a QIR generation error in the vscode extension. Currently, only a pop-up with the error message appears (#1547, #1552).
- [x] Provide a visual cue in the vscode extension to indicate QIR generation is in progress. (#1591)
- [x] Extend `@Config` syntax to allow performing `not` unary operator (#1564)
- [x] Error messages that refer to support by current "target" should clarify when it is meant to be "target profile" vs "submission target" (it's usually the former) (#1575)
- [x] Add error specific help links for RCA check pass errors (current all redirect to the wiki) (#1594)

<s>Add lints that nudge users to use more robust patterns when compiling for hardware targets</s> Lint suggestions moved to #1333 for tracking.
