### ISSUE TITLE
Introduce High-level Intermediate Representation (HIR)

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp#166]
We need an HIR in order to embed additional information in the data structure (such as type information and resolved symbols), as well as to allow the HIR to deviate from the Syntax Tree (which should stay 1:1 with actual Q# syntax).

```[tasklist]
### Tasks
- [x] Introduce initial HIR as copy of AST (#163)
- [x] Include resolved symbols in HIR (#173)
- [x] Include type information in HIR (#179)
```
