### ISSUE TITLE
Q# 2.0 Tracking Issue

### ISSUE THREAD

**Issue by sezna** [microsoft/qsharp#2049]
This issue tracks the tasks we'd like to have done before the release of Q# 2.0. 

- [ ] #2048
- [ ] Deprecate Explicit Namespaces (no issue yet)
- [ ] Deprecate use qubit blocks
- [ ] `w/` syntax
- [ ] Old UDT syntax
- [ ] Deprecate `Microsoft.Quantum.*` libraries

**Comment by sezna** [comment]
# Process of Upgrading Q# Syntax

For anything breaking, primarily the removal or modification of existing Q# syntax, we want to be in the following state before Q# 2.0:

1. A lint warning will inform the user that something is deprecated.
2. The v2-preview-syntax feature flag allows the user to opt-in to v2 syntax, meaning that the aforementioned lints become compile errors.
3. There needs to be a clearly documented path to go from deprecated syntax to v2 syntax. Ideally, there's also a quick fix attached to the lint to make this even easier.

We should define a minimum deprecation time period such that items are deprecated for at least that long before they are removed. During this period, there should also be new syntax available.
