### ISSUE TITLE
Refactor compiler crate structure

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp#214]
The compiler folder currently has lots of examples of code that follows a similar pattern of "create a package store, call compile on std, run passes, insert into store, compile user code, run passes, insert into store." Ian abstracted some of that into common patterns in stateful and stateless interpreter, but there are still plenty of examples of it. As as we refine error reporting and introduce more passes with more errors, we need to have a way to track source files and correlate them back to errors to relate to these call patterns. It became clear that what we want is a qsc library that abstracts these common patterns, rather than copying them or creating additional dependencies between crates with helper functions that are broader than their containing crate's purpose. So we'd like to do the following refactor:

```[tasklist]
### Tasks
- [x] Move qsi into qsc as a binary output, such that the qsc crate defines the common compiler library and two binary outputs, qsc.exe and qsi.exe. (#219)
- [x] Move the stateless and stateful evaluator wrappers up the hierarchy into the qsc crate, such that qsc_eval takes HIR as input instead of strings. (#219)
- [x] <s>Move the run_default_passes out of qsc_passes crate so that the crate just exposes each pass individually (which it already does).</s> run_default_passes is used by test infra, so we should leave it where it is to avoid duplication and/or circular dependencies.
- [x] Use the qsc crate as the host of the common library to handle bundling errors, caching stdlib compilations, running the default passes in the expected order, caching source code for correlation back to errors, etc. Effectively becomes the top-level compiler library for functionality that spans (pun intended) across the other crates and exposes the right utility functions to take in strings and either check or execute code, returning the right Rust results/errors for Rust consumers. (#219)
- [x] Update qsc_wasm to use the common API from qsc library rather than dependencies on the other individual crates, and then move it out of the compiler folder into a top level wasm folder. (#256)
```

After this, the top-level folders would be compiler, katas, library, npm, playground, samples, and wasm. Anything outside of the compiler folder is expected to use qsc (either the library if Rust interop is an option or the produces exes) as the way to access the compiler and evaluator features.
