### ISSUE TITLE
Create production-ready content for Katas

### ISSUE THREAD

**Issue by cesarzc** [microsoft/qsharp#298]
There are two aspects to creating production-ready content for katas.

**Infrastructure support**:
- [x] 🟢 Composition using a single markdown file (#434).
- [x] 🟢 Expand macros to compose katas (#476).

**Katas content**

 The following list contains the proposed list of tutorials to create (in order):
- [x] 🟢 The Qubit (#495)
    - Corresponds to https://github.com/microsoft/QuantumKatas/tree/main/tutorials/Qubit.
    - Contains images (`DumpMachine` visualizations), but they can be replaced by improving the description of the interactive example.
    - It will be merged with the visualization tools tutorial that corresponds to https://github.com/microsoft/QuantumKatas/tree/main/tutorials/VisualizationTools
- [x] 🟢  Single-qubit gates (#475)
    - Corresponds to https://github.com/microsoft/QuantumKatas/tree/main/tutorials/SingleQubitGates
- [x] 🟢  Multi-qubit systems (#440)
    - Corresponds to https://github.com/microsoft/QuantumKatas/tree/main/tutorials/MultiQubitSystems
- [x] 🟢 Muti-qubit gates (#558)
    - Corresponds to https://github.com/microsoft/QuantumKatas/tree/main/tutorials/MultiQubitGates
- [x] 🟢 Single-qubit system measurements (#405)
    - Corresponds to https://github.com/microsoft/QuantumKatas/tree/main/tutorials/SingleQubitSystemMeasurements
- [x] 🟢 Multi-qubit system measurements (#416)
    - Corresponds to https://github.com/microsoft/QuantumKatas/tree/main/tutorials/MultiQubitSystemMeasurements
- [x] 🟢 Random number generation (#438)
    - Corresponds to https://github.com/microsoft/QuantumKatas/tree/main/tutorials/RandomNumberGeneration
- [x] 🟢 Oracles (#435)
    - Corresponds to https://github.com/microsoft/QuantumKatas/tree/main/tutorials/MultiQubitSystemMeasurements

Code:
- 🟢 Done.
- 🟡 In progress.
- 🔴 Not started.
- ❓ Determine whether it is needed.

How to support for katas:
- Links to katas, exercises or sections can be done in markdown through the link syntax where the value of the link is the id of the item (e.g. `[Single qubit gates kata](single_qubit_gates)`).
- Images/video are currently not supported.

**Comment by cesarzc** [comment]
First batch of content has been merged to `main`.
