### ISSUE TITLE
Debugger

### ISSUE THREAD

**Issue by idavis** [microsoft/qsharp#420]
This is a tracking issue for adding debugger support for Q#.

For a debugger to function across Monaco, VSCode, and potentially in a REPL, the core debugging functionality needs to reside in a new interpreter. As a first cut we can model this on the stateless interpreter. If we wish to look into supporting the REPL or (VS Code debugger REPL) we need to look at what it will take to do side effect free evaluation. This would also potentially power conditional breakpoints.

## Components involved

1. **Compiler (QSC)**: Create a new debugger interpreter alongside the current stateful and stateless evaluator. We should be able to deprecate one or both eventually with the debugger running in execution mode and not using any breakpoint functionality.
2.  **WASM**: create a decorator around the debugger which translates the rust data structures into JS compatible values. The API should have the same shape and just be a data marshaling shim.
3.  **npm package**: This is the same package used by the playground that incorporates the Q# compiler. A new interface will be added to provide access to the debugger which handles the loading of the wasm shim and provides a strongly typed interface for consumption by Monaco and VS Code.
4. **VS Code extension**: Implementation of the VS Code debug adapter APIs mapping the calls to the shim and setting up debugging capabilities.
5. **Playground**: Similar to VS Code, the debugger needs to be wired up to the Monaco editor extension points in the playground. This will require more changes to the way we hook into Monaco as it doesn't natively support debugging extensions. The extent of the work to be done here is TBD.

```mermaid
%%{init: { "flowchart": { "nodeSpacing": 3 } } }%%
flowchart TD

subgraph JS
  playground[Playground]
  vscode[VS Code extension]
  website[Website]
  npm[npm package]
end

subgraph Rust
  repl[REPL?]
  wasm["JS bindings (WASM)"]
  debugger[Debugger]
  compiler[Compiler]
end

playground
vscode
website

playground-->npm
vscode-->npm
website-->npm

npm-->wasm
wasm-->debugger
repl-->debugger
debugger-->compiler
```

## Implementation plan

The initial plan is to support the base scaffolding and core features. Several of the triage and out of scope features require side effect free expression evaluation (log points, hit/conditional breakpoints, etc.). After the core features are functional for VS Code, the base functionality can be exposed for Monaco.

- Scaffolding:
  - [ ] Set up debugger with minimal end-to-end interface allowing the `F5` execution of current Q# file open in editor, no debugging
- Core Features (compiler and VS Code)
  - [ ] Get available breakpoint locations from target
  - [ ] Set breakpoints
  - [ ] Validate pre-set breakpoints on launch
  - [ ] Run program with debugging stopping at breakpoints
  - [ ] Call stack information
  - [ ] Locals
  - [ ] Stepping
    - [ ] In
    - [ ] Over
    - [ ] Out
- Other features for triage
  - Disassembly
  - Conditional Breakpoints
  - Hit Conditional Breakpoints
  - Side effect free evaluation of hovers
  - Function Breakpoints
  - Custom launch configurations (launch.json)
  - Step/breakpoint granularity
  - Debug REPL
    - Completion requests
    - side effect free evaluation
  - Restarting debugging
  - Setting expression/variable values (modifying runtime state)
  - Viewing quantum state
  - Logpoint messages
- Out of scope
  - Step back
  - Restart frame
  - Go to targets
  - Step in targets
  - Module to package mapping and request support
 
## Resources
- [Debugger Extension guide](https://code.visualstudio.com/api/extension-guides/debugger-extension)
- [Debug Adapter Protocol](https://microsoft.github.io/debug-adapter-protocol/)

**Comment by idavis** [comment]
@sezna It is a tracking issue for work. Smaller issues are created for those work items. We can discuss if we want to maintain the tracking issue.
