### ISSUE TITLE
Katas infrastructure

### ISSUE THREAD

**Issue by spignorel** [microsoft/qsharp#50]
```[tasklist]
### Tasks
- [x] Initial Katas Tasks and Validation (#93, #100)
- [x] Build infrastructure for katas (#160)
- [ ] #149
- [x] Add new types of content to katas (#261) (#283)
```
