### ISSUE TITLE
Expand Q# samples to include both basic quantum algorithms and basic language usage snippets

### ISSUE THREAD

**Issue by cesarzc** [microsoft/qsharp#507]
This issue tracks the progress towards significantly expanding the number of Q# samples.

**General tasks**:
- [x] Separate samples between quantum algorithms and language usage, adding documentation comments to existing ones. (@cesarzc) (#521).

**Quantum algorithms**:
- [x] Quantum Hello World (@cesarzc) (#531)
- [x] QRNG (@cesarzc) (#521)
- [x] Bell state (@cesarzc) (#521)
- [x] Teleportation (@cesarzc) (#521)
- [x] Deutsh-Jozsa (@cesarzc) (#521)
- [x] Bernstein-Vazirani (@cesarzc) (#521)
- [x] Hidden shift (@cesarzc) (#521)
- [x] Grover (@cesarzc) (#521)
- [x] Shor (@cesarzc) (#521)
- [x] Random bit (@cesarzc) (#570)
- [x] Superposition (@cesarzc) (#570)
- [x] Entanglement (@cesarzc) (#570)
- [x] Measurement (@sezna) (#586)
- [x] Joint measurement (@sezna) (#586)
- [x] Superdense coding (@sezna) (#586)

**Language usage**:
- [x] Getting started (aka minimal) (@cesarzc) (#521)
- [x] Comments (@sezna) (#515)
- [x] Namespaces (@sezna) (#515)
- [x] Operations (@sezna) (#515)
- [x] Functions (@sezna) (#515)
- [x] Entry point (@sezna) (#515)
- [x] Specializations: body, adjoint, controlled (@sezna) (#515)
- [x] Data types (@sezna) (#522)
- [x] Data type: Qubit  (@sezna) (#522)
- [x] Data type: Result  (@sezna) (#522)
- [x] Data type: Pauli  (@sezna) (#522)
- [x] Data type: Unit  (@sezna) (#522)
- [x] Data type: Bool  (@sezna) (#522)
- [x] Data type: Int  (@sezna) (#522)
- [x] Data type: BigInt  (@sezna) (#522)
- [x] Data type: Double  (@sezna) (#522)
- [x] Data type: Range  (@sezna) (#522)
- [x] Data type: String (include concatenation and interpolation)  (@sezna) (#522)
- [x] Data type: Array (include slicing).  (@sezna) (#522)
- [x] Data type: Tuple (include unwrap)  (@sezna) (#522)
- [x] Type declarations (include access via name using the :: operator and via deconstruction using the ! operator)  (@sezna) (#590)
- [x] Variables: let, mutable  (@sezna) (#590)
- [x] Quantum memory: use, borrow (@sezna) (#590)
- [x] Return statement (@sezna) (#590)
- [x] Fail statement (@sezna) (#590)
- [X] For loops  (@ScottCarda-MS) (#537)
- [X] While loops  (@ScottCarda-MS) (#537)
- [X] Repeat loops  (@ScottCarda-MS) (#537)
- [x] Conditional branching: if, elif, else (@sezna) (#590)
- [x] Within Apply (@sezna) (#590)
- [X] Operator: copy and update (w/ <-)  (@ScottCarda-MS) (#589)
- [X] Operator: range (..)  (@ScottCarda-MS) (#589)
- [X] Operators: logical (and, or, not)  (@ScottCarda-MS) (#589)
- [X] Operators: bitwise (|||, ^^^, &&&, >>>, <<<, ~~~)  (@ScottCarda-MS) (#589)
- [X] Operators: comparison (==, != <, <=, >, >=)  (@ScottCarda-MS) (#589)
- [X] Operators: arithmetic (+, -, *, /, %, ^, - [negative])  (@ScottCarda-MS) (#589)
- [x] Lambda expressions (function -> and operation =>) (@sezna) (#590)
- [x] Partial applications (@sezna) (#590)
- [x] Diagnostics (@sezna) (#590)

**Comment by cesarzc** [comment]
All samples must have doc comments at the beginning of the file in the following format:
```qsharp
/// # Sample
/// Bell state
///
/// # Description
/// Bell states or EPR pairs are specific quantum states of two qubits
/// that represent the simplest (and maximal) examples of quantum entanglement.
/// The following Q# code implements one of these Bell states.
```

**Comment by cesarzc** [comment]
Closing since all the basic samples have been completed.
