### ISSUE TITLE
Compiler Core Features

### ISSUE THREAD

**Issue by spignorel** [microsoft/qsharp#54]
```[tasklist]
### Tasks
- [x] Abstract Syntax Tree (#2)
- [x] Parser (#4, #5, #15, #16, #17, #18, #19, #20, #21, #24, #28, #29)
- [x] Symbol resolution (#27, #60)
- [x] Source dependency support (#32, #46, #53)
- [x] implicitly open some standard library (#64)
```
