### ISSUE TITLE
Evaluator Core Features

### ISSUE THREAD

**Issue by spignorel** [microsoft/qsharp#55]
```[tasklist]
### Tasks
- [x] Support Critical Language Features (#31, #37, #44, #58, #67, #68, #78, #84, #88, #92)
- [x] Use Sparse simulator for gates (#69, #78)
- [x] Math intrinsic support (#96)
```
