### ISSUE TITLE
Support base profile QIR codegen

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp#571]
This is a tracking issue to cover the work for base profile QIR codegen.

```[tasklist]
### Tasks
- [x] Introduce gate-collector simulator for code from compliant Q# (#500)
- [x] Use conditional compilation and analysis pass to restrict to base profile compliant code (#494)
- [x] Introduce basic decomposition .ll for hardware compatibility (#500)
- [x] Update measurement patterns for better decomposition (#564)
- [ ] #568
- [x] Improve "not found" error when related to target-specific conditional compilation (#573)
- [ ] https://github.com/microsoft/qsharp/issues/572
- [x] Introduce bindings for QIR codegen in qsharp Python module (#588)
- [ ] https://github.com/microsoft/qsharp/issues/574
```
