### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by spignorel** [microsoft/qsharp#61]
```[tasklist]
### Tasks
- [x] Introduce NPM package and test environment (#82)
- [x] Refactor NPM package, async support (#203)
- [ ] https://github.com/microsoft/qsharp/issues/57
```
