### ISSUE TITLE
Specialization Generation and Conjugate Passes

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp#63]
```[tasklist]
### Tasks
- [x] Adjoint self generation (#158)
- [ ] https://github.com/microsoft/qsharp/issues/142
- [x] Controlled distribute generation (#129)
- [x] Quantum logic separation (#190)
- [x] Adjoint inverse generation (#190, #192)
- [x] Conjugate expansion (#215)
```
