### ISSUE TITLE
Validation Pass

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp#71]
As temporary protection before type inference and broader feature support exists, we need some validation passes that check for specific disallowed patterns in Q# that warns users early and protects later transformation passes from needing to handle invalid patterns.

```[tasklist]
### Tasks
- [x] Reject operations that are `Adj` and/or `Ctl` but do not return `Unit` (#79)
- [x] Disallow partial application (#79)
- [x] Disallow callables as arguments (#79)
- [x] Disallow lambdas (#79)
- [x] Disallow type holes (#79)
```
