### ISSUE TITLE
Initial Q# Package System

### ISSUE THREAD

**Issue by sezna** [microsoft/qsharp#883]
# Q# Package System

## Definitions
* **package**: an exported or imported Q# project. 
* **package system**: the canonical and conventional way to export or import Q# projects, as packages.

Note the above constrained definitions -- we are not trying to build a registry or robust SemVer-based system at this point. 

## Objectives
* Unblock code-sharing for library authors.
* Provide alternative canonical Microsoft libraries that are not the standard library
* Provide a conventional system that supports the common use case of sharing publicly available code
* Don't immediately support private libraries, that can be a follow-on task
* Be able to construct a complete list of sources and fetch them before compilation begins

## User Stories
* As a hardware partner, I would like to publish an algorithm, as a Q# library, to showcase my hardware's capabilities.
* As a Q# author, I would like to import code without having to copy-paste it into my project.

## Potential Design
We initially only support shared code on GitHub. We use the GitHub REST API, which supports listing directories and cloning subfolders. This helps us avoid `libgit2`, which is impermissively licensed, and any native git implementations which may not work on all of our scenarios.

To import a Q# package, the user will add an entry to their manifest file's `dependencies` property. This will look similar to the `dependencies` property in a package.json. [We could even use their GitHub URL shorthand.](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#github-urls), or we could just use GitHub URLs.

We will browse to that URL, look for a `qsharp.json` in the specified subfolder, or the root if no subfolder is specified, and parse the dependencies of that package. We will continue this process, browsing to them and parsing their manifests, with all dependencies until we have a complete graph of direct dependencies and transitive dependencies. At this stage, we will load all of these sources into memory and begin compilation as normal. In non-web scenarios, we may be able to cache these dependencies to disk, but in web scenarios, they may be cached in the state of the language service.

Related: #73 
```[tasklist]
### Tasks
- [ ] Tests: test dependency ordering edge cases with different language features enabled, etc
- [ ] Tests: test that entry points in libraries are not used
- [x] wire up all scenarios
- [x] work out TODOs on alex's branch
- [ ] telemetry
- [ ] Load transitive deps for qsc
- [ ] Load transitive deps for qsi
- [x] go-to-def and breaking _into_ things don't work
- [ ] https://github.com/microsoft/qsharp/pull/1651#discussion_r1646331561 change this test
```

**Comment by minestarks** [comment]
`feature/party` tasks

- [ ] support `files` property in qsharp.json for package authoring
  - [ ] require it if `packageType == "lib"`
  - [ ] warn about missing source files items after crawling directory on disk
  - [ ] provide way to automatically add missing source files to `qsharp.json`
