### ISSUE TITLE
Performance Tracking

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp#895]
We discussed some ideas for performing some performance tracking on the repository and want to capture that here with an overarching issue. The idea is to provide both proactive and reactive mechanisms for evaluating perf and make it easy for us as a team to develop with performance in mind. To get us started, here's some tasks we can use initially and expand on as we discover more that will work for us.

- [x] Update existing Benches execution in pipeline to run against both PR payload and main branch in order to establish local improvement/regression percentage rather than just raw perf number.
- [x] Capture output from Benches execution as pipeline artifact for avoid having to dig into logs
- [ ] Utilize Criterion settings to avoid noisy regression/improvement (more runs, wider tolerances, etc)
- [ ] Capture developer workflow best practices for perf testing in dev-focused readme.md

Possible areas of investment in the future (if the above show promise):
 - Investigate available tools/infrastructure to have GitHub Workflow visualize trendlines
 - Use both native and WASM benches to see perf of different binaries
 - Investigate whether auto-filed issues or pipeline failures are the right way to flag performance issues
 - Use telemetry to aggregate performance picture of actual user experience

**Comment by sezna** [comment]
I think the majority of this has been done, but there is of course still a long tail of performance metric tracking that we could pursue. Closing this as done for now. Perhaps @orpuente-MS can file an issue to describe his improved benchmarking work?
